### ISSUE TITLE
Query was already executed: Review.findOne({ _id: new ObjectId(\"62b44ca73c5b3f0162267ea2...",

### ISSUE THREAD

**Issue by rohit-13** [jonasschmedtmann/complete-node-bootcamp#147]
```json
{
    "status": "error",
    "error": {
        "originalStack": "Error\n    at model.Query._wrappedThunk [as _findOne] (/media/rohit/SSD_D1/Project/natours-app/node_modules/mongoose/lib/helpers/query/wrapThunk.js:25:28)\n    at /media/rohit/SSD_D1/Project/natours-app/node_modules/kareem/index.js:279:20\n    at _next (/media/rohit/SSD_D1/Project/natours-app/node_modules/kareem/index.js:103:16)\n    at /media/rohit/SSD_D1/Project/natours-app/node_modules/kareem/index.js:508:38\n    at processTicksAndRejections (node:internal/process/task_queues:78:11)",
        "statusCode": 500,
        "status": "error"
    },
    "message": "Query was already executed: Review.findOne({ _id: new ObjectId(\"62b44ca73c5b3f0162267ea2...",
    "stack": "MongooseError: Query was already executed: Review.findOne({ _id: new ObjectId(\"62b44ca73c5b3f0162267ea2...\n    at model.Query._wrappedThunk [as _findOneAndUpdate] (/media/rohit/SSD_D1/Project/natours-app/node_modules/mongoose/lib/helpers/query/wrapThunk.js:21:19)\n    at /media/rohit/SSD_D1/Project/natours-app/node_modules/kareem/index.js:279:20\n    at _next (/media/rohit/SSD_D1/Project/natours-app/node_modules/kareem/index.js:103:16)\n    at /media/rohit/SSD_D1/Project/natours-app/node_modules/kareem/index.js:508:38\n    at processTicksAndRejections (node:internal/process/task_queues:78:11)"
}

**Comment by muyeenulislam** [comment]
Attach .clone() after .findOne(). Worked for me

`reviewSchema.pre(/^findOneAnd/, async function (next) {
  this.r = await this.findOne().clone();
  // console.log(this.r);
  next();
});`

**Comment by AgiriTaofeek** [comment]
Thanks man,  it worked like magic

**Comment by Mae6e** [comment]
Mongoose throws a 'Query was already executed' error when a given query is executed twice.
If you're absolutely sure you want to execute the exact same query twice, you can use clone()

**Comment by amritaB23** [comment]
if want to execute a query twice use clone() 

 this.result = await this.findOne().clone();

**Comment by govindrevenger** [comment]
can anyone tell me how this this.result = await this.findOne() query runs twice in reviewSchema.pre(/^findOneAnd/, async function (next) { this.r = await this.findOne().clone(); // console.log(this.r); next(); }); this query middleware @Mae6e @amritaB23 @muyeenulislam

**Comment by Mae6e** [comment]
@govindrevenger 

findOne is a method used to find and retrieve one document that matches the query criteria from the MongoDB database.
clone() is a method that is used to create a deep copy of the selected document from the MongoDB database.

So, await this.findOne().clone() means that the program will wait until the findOne() method retrieves a document from the database that matches the query criteria, and then clones the document to create a new copy of it.

**Comment by manohySr** [comment]
> Attach .clone() after .findOne(). Worked for me
> 
> `reviewSchema.pre(/^findOneAnd/, async function (next) { this.r = await this.findOne().clone(); // console.log(this.r); next(); });`

Thanks, it works

**Comment by Ala-Ben-Aissia** [comment]
No need for the pre query middleware.
You can simply use the post query hook since this will include the recent updated review :

reviewSchema.post(/^findOneAnd/, async function () {
    const review = await this.clone().findOne().exec();
    // console.log(this.model === review.constructor); // true
    this.model.calcAvgRatings(review.tour);
});

**Comment by gideondakore** [comment]
I found the solution in the mongoose documentation and it works very fine:  https://mongoosejs.com/docs/middleware.html#notes

This is the solution that you need for it to work in the course:

```
const r = await this.model.findOne(this.getQuery());
console.log(r);
```

OR

```
const r = await this.model.findOne();
console.log(r);
```

OR

```
const r = await this.findOne().clone()
console.log(r)
```

OR

```
const r = await this.clone().findOne()
console.log(r)
```

**NOTE THIS EDIT PLEASE**

There is a subtle bug that you will face when you use this approaches
 
```
const r = await this.model.findOne();
console.log(r);
```
and

```
const r = await this.findOne().clone()
console.log(r)
```

SO PLEASE USE ONE OF THESE:

```
const r = await this.model.findOne(this.getQuery());
console.log(r);
```
OR

```
const r = await this.clone().findOne()
console.log(r)
```

==========================================================
In case you are wondering what the bug was, when ever you use those approach that I listed as a bug, you will find out that everything works normal but when you try deleting or updating a review, it does not update "ratingsAverage" and "ratingsQuantity" as expected and remain as the previous state because it doesn't get the right references to the current review/document you wanted to delete or update. Using the later approaches either cloned it before the "findOne" method is call or pass in the "this.getQuery" to explicitly pass in the id

**Comment by LaxmanSingh07** [comment]
Unsubscribe
