### ISSUE TITLE
Can't find the name property inside the err object.

### ISSUE THREAD

**Issue by saysonjerald** [jonasschmedtmann/complete-node-bootcamp#55]
It seems like Express removed the name property inside the err object. Can anyone confirm this?  
This is how it looks like on my Postman 

```
{
    "status": "error",
    "error": {
        "stringValue": "\"5f9618b492f2d81f5cb032829\"",
        "kind": "ObjectId",
        "value": "5f9618b492f2d81f5cb032829",
        "path": "_id",
        "reason": {},
        "statusCode": 500,
        "status": "error"
    },
    "message": "Cast to ObjectId failed for value \"5f9618b492f2d81f5cb032829\" at path \"_id\" for model \"Tour\"",
    "stack": "CastError: Cast to ObjectId failed for value \"5f9618b492f2d81f5cb032829\" at path \"_id\" for model \"Tour\"\n    at model.Query.exec (C:\\Users\\SayJee\\OneDrive\\Desktop\\Nodles\\complete-node-bootcamp-master\\4-natours\\practice\\node_modules\\mongoose\\lib\\query.js:4352:21)\n    at model.Query.Query.then (C:\\Users\\SayJee\\OneDrive\\Desktop\\Nodles\\complete-node-bootcamp-master\\4-natours\\practice\\node_modules\\mongoose\\lib\\query.js:4444:15)\n    at processTicksAndRejections (internal/process/task_queues.js:97:5)"
}
```  
As you can see in the code above, there is no 'name' property,, therefore we can't use this code below anymore and it's outdated. 
`if(error.name === 'CastError') error = handleCastErrorDB(error);`
i even tried to make a `console.log(error.name)` and you know what? it returns `undefined`. 

Is there an alternative solution for this? Thanks for checking out.

**Comment by Yash1256** [comment]
Yup the same is happening with me... @saysonjerald. @jonasschmedtmann Can u please confirm this and update it in the video too..

**Comment by nvispute** [comment]
I think i understand what is happening here.. 
you See the  functions in our ErrorController.js  `handleCastErrorDB()` OR `handleDuplicateFieldsDB(`) are thrown by Mongoose or MongoDB and propbably it is they who must have stopped emitting error.name value and switched to StatusCodes insteads becasue In our ErrorController.js we do have some errors checked by statuscode before we call the functions in the if loops such as this one
`if (error.code === 11000) error = handleDuplicateFieldsDB(error);`

In @saysonjerald  code you can see that we do have statuscode, however In the "stack": we do have the string starting with "CastError"
They must have done it to prevent information leakage as stack is mostly used during development and not during Prod.

Quick Fix can be to completly switch over to statusCode instead of name and check the expected name value inside of the stack String starting with that value to verify.

**Comment by SENYa-408** [comment]
I fixed it using the 2nd option suggested by @nvispute

I put this code after the `error` variable declaration:
`if (err.stack.indexOf('CastError', 0) === 0) error.name = 'CastError';`

Hope it works for you

**Comment by a-aiman** [comment]
> I think i understand what is happening here.. You See the functions in our ErrorController.js `handleCastErrorDB()` OR `handleDuplicateFieldsDB(`) are thrown by Mongoose or MongoDB ([Official Doc Link for Error's coming from mongoDB](https://docs.atlas.mongodb.com/api#errors)) and propbably it is MongoDb who must have stopped emitting error.name value and switched to StatusCodes instead as seen in the Official Doc Link. In our ErrorController.js we do have some errors checked by statuscode before we call the custom functions in the if loops such as this one `if (error.code === 11000) error = handleDuplicateFieldsDB(error);`
> 
> In Code shared by @saysonjerald you can see that we do have statuscode, Also in the "stack": you can see we have a string starting with "CastError" I think they must have done it to prevent information leakage while in prod mode as stack is mostly used during development and not during Prod.
> 
> Quick Fix can be to completly switch over to statusCodes Option 1 Inside our errorController.js, call the custom functions in the `If` statements with err.statusCode instead of err.name Option 2 (Long Way) We can Take the String inside of the stack and check for the string starting value with the previous names we already have defined in our if block
> 
> Or a combination of both...

I don't think they change the error object. It's still there. What actually happen is because we are simply shallow copying the object using spread operator. The problem is that the name is living inside the prototype of the error object. The solution is to use Object.create() instead of the spread operator

`if (process.env.NODE_ENV === 'development') {
    sendErrorDev(err, res);
  } else {
    // let error = {...err} Won't work because it is shallow copying the properties on the object ONLY and returns new obj
    let error = Object.create(err); // This will set 'err' obj as the proto of the new 'error' object
    console.log(err.__proto__.name); // Output: 'CastError' because name is living inside the prototype, not the object
    console.log(error.name); // Output: 'CastError' because of prototypal inheritance
    if (error.name === 'CastError') error = handleCastErrorDB(error);
    sendErrorProd(error, res);
  }`

sources: https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Error/name
Copying with spread operator as far as i'm concerned returns a new object and therefore does not have any prototypal inheritance of the original object.

**Comment by a-aiman** [comment]
> I think i understand what is happening here.. You See the functions in our ErrorController.js `handleCastErrorDB()` OR `handleDuplicateFieldsDB(`) are thrown by Mongoose or MongoDB ([Official Doc Link for Error's coming from mongoDB](https://docs.atlas.mongodb.com/api#errors)) and propbably it is MongoDb who must have stopped emitting error.name value and switched to StatusCodes instead as seen in the Official Doc Link. In our ErrorController.js we do have some errors checked by statuscode before we call the custom functions in the if loops such as this one `if (error.code === 11000) error = handleDuplicateFieldsDB(error);`
> 
> In Code shared by @saysonjerald you can see that we do have statuscode, Also in the "stack": you can see we have a string starting with "CastError" I think they must have done it to prevent information leakage while in prod mode as stack is mostly used during development and not during Prod.
> 
> Quick Fix can be to completly switch over to statusCodes Option 1 Inside our errorController.js, call the custom functions in the `If` statements with err.statusCode instead of err.name Option 2 (Long Way) We can Take the String inside of the stack and check for the string starting value with the previous names we already have defined in our if block
> 
> Or a combination of both...

I don't think they change the error object. The name property is still there. What actually happen is because we are simply shallow copying the err object using spread operator. The problem is that the name property is inside the prototype of the err object but copying with spread operator returns a new object and therefore the prototypal inheritance is lost. The solution is to use Object.create() instead of the spread operator

![err](https://user-images.githubusercontent.com/87350788/137608388-567ac56f-3aee-490d-ae1d-24c667608fc9.png)

sources:
- https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Error/name
- https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Operators/Spread_syntax#spread_in_object_literals

**Comment by pranjalg131** [comment]
@a-aiman Thanks for the solution , I was frustrated for 1 hour trying to think what is wrong , turns out this is one of those occasions where destructuring backfires.

**Comment by YTeyddie22** [comment]
@amiraiman. Thanks for the help.

**Comment by AbdourahamaneIssakaSani** [comment]
> > I think i understand what is happening here.. You See the functions in our ErrorController.js `handleCastErrorDB()` OR `handleDuplicateFieldsDB(`) are thrown by Mongoose or MongoDB ([Official Doc Link for Error's coming from mongoDB](https://docs.atlas.mongodb.com/api#errors)) and propbably it is MongoDb who must have stopped emitting error.name value and switched to StatusCodes instead as seen in the Official Doc Link. In our ErrorController.js we do have some errors checked by statuscode before we call the custom functions in the if loops such as this one `if (error.code === 11000) error = handleDuplicateFieldsDB(error);`
> > In Code shared by @saysonjerald you can see that we do have statuscode, Also in the "stack": you can see we have a string starting with "CastError" I think they must have done it to prevent information leakage while in prod mode as stack is mostly used during development and not during Prod.
> > Quick Fix can be to completly switch over to statusCodes Option 1 Inside our errorController.js, call the custom functions in the `If` statements with err.statusCode instead of err.name Option 2 (Long Way) We can Take the String inside of the stack and check for the string starting value with the previous names we already have defined in our if block
> > Or a combination of both...
> 
> I don't think they change the error object. The name property is still there. What actually happen is because we are simply shallow copying the err object using spread operator. The problem is that the name property is inside the prototype of the err object but copying with spread operator returns a new object that does not include the prototype of the object that it is copying. The solution is to use Object.create() instead of the spread operator
> 
> ![err](https://user-images.githubusercontent.com/87350788/137608388-567ac56f-3aee-490d-ae1d-24c667608fc9.png)
> 
> sources:
> 
> * https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Error/name
> * https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Operators/Spread_syntax#spread_in_object_literals

Thanks @amiraiman. Your answer helped however I got an empty `error` object in case of a duplicated field in mongodb. And here what I tried:
 ```
let error = Object.create(err, Object.getOwnPropertyDescriptors(err));

```
This adds the rest of properties of `err` object, after those in the prototype.

**Comment by jonasschmedtmann** [comment]
Hey there,

This is an automatic reply. I know no one likes to get these, but I get an incredible amount of email, and I'd rather spend my time doing what I do best: working on bringing you the best courses I possibly can 😎

So the following points should reply to 90% of emails I get:

[1] FOR STUDENTS

👉 Do you have a problem with one of my courses? Please post it in the Q&A section, that's where all problems will get solved 😃
👉 Are you looking for career advice/next steps? Again, the course Q&A is the place to go. There, everyone can benefit from replies.
👉 Can't find your certificate? Please see this article<https://support.udemy.com/hc/en-us/articles/229603868-How-to-Download-Your-Certificate-of-Completion-on-a-Browser->.
👉 Are you looking for an e-book? The e-book was replaced many years ago by my resources page<https://codingheroes.io/resources/>.
👉 Are you looking to get a course for free? I sometimes run giveaways on my Discord channel<https://discord.gg/uhMkpf4>, but in general I don't give out free coupons, simply because it's unfair to people who actually bought the course.
👉 Are you looking for my older newsletters? I don't have them on my website currently. Maybe I will at some point, so check my website again later.

[2] FOR MARKETING PEOPLE

👉 Do you want me to publish my courses on your platform/create new courses/write a book/etc.? I won't, I am working 100% exclusive with Udemy.
👉 Do you want to help me with marketing my courses? I'm not interested, Udemy does a stellar job at promoting (really, don't waste your time trying to convince me).

If you have something important that's not covered here, just reply to this email, and I might answer it at some point (I can't guarantee it 😅).

Have a wonderful day!

Jonas

On January 2, 2023 at 7:07 PM UTC, Abissa ***@***.***) wrote:

I think i understand what is happening here.. You See the functions in our ErrorController.js handleCastErrorDB() OR handleDuplicateFieldsDB() are thrown by Mongoose or MongoDB (Official Doc Link for Error's coming from mongoDB<https://docs.atlas.mongodb.com/api#errors>) and propbably it is MongoDb who must have stopped emitting error.name value and switched to StatusCodes instead as seen in the Official Doc Link. In our ErrorController.js we do have some errors checked by statuscode before we call the custom functions in the if loops such as this one if (error.code === 11000) error = handleDuplicateFieldsDB(error);
In Code shared by @saysonjerald<https://github.com/saysonjerald> you can see that we do have statuscode, Also in the "stack": you can see we have a string starting with "CastError" I think they must have done it to prevent information leakage while in prod mode as stack is mostly used during development and not during Prod.
Quick Fix can be to completly switch over to statusCodes Option 1 Inside our errorController.js, call the custom functions in the If statements with err.statusCode instead of err.name Option 2 (Long Way) We can Take the String inside of the stack and check for the string starting value with the previous names we already have defined in our if block
Or a combination of both...

I don't think they change the error object. The name property is still there. What actually happen is because we are simply shallow copying the err object using spread operator. The problem is that the name property is inside the prototype of the err object but copying with spread operator returns a new object that does not include the prototype of the object that it is copying. The solution is to use Object.create() instead of the spread operator

[err]<https://user-images.githubusercontent.com/87350788/137608388-567ac56f-3aee-490d-ae1d-24c667608fc9.png>

sources:

  *   https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Error/name
  *   https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Operators/Spread_syntax#spread_in_object_literals

Thanks @amiraiman<https://github.com/amiraiman>. Your answer helped however I got an empty error object in case of a duplicated field in mongodb. And here what I tried:

let error = Object.create(err, Object.getOwnPropertyDescriptors(err));



This adds the rest of properties of err object, after those in the prototype.

**Comment by renato76** [comment]
Abissa, thank you, this finally solved it for me aftwe days of trying to debug this!

Just to clarify, using the suggested solution of :
  let error = Object.create(err)

This solved it!
